### ISSUE TITLE
Allow LEFT/RIGHT JOIN and UNION

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/go-sqlparser#28]
We should also consider `CROSS JOIN` if there are no downsides.

**Comment by brunocalza** [comment]
Going to add all JOIN operators supported in SQLite and

<img width="709" alt="Screen Shot 2022-11-21 at 17 27 31" src="https://user-images.githubusercontent.com/1233473/203152076-089ac369-3abe-4475-a1eb-fb395ac883de.png">

all compound operators

<img width="387" alt="Screen Shot 2022-11-21 at 17 28 21" src="https://user-images.githubusercontent.com/1233473/203152178-5270e924-3a3e-4504-bbfd-6057e648e9a3.png">

wdyt? @jsign @carsonfarmer

**Comment by carsonfarmer** [comment]
I'm for it. I think our original thinking around _not_ supporting them was that we wanted to keep the spec small, and needed some use cases to support it. I think we have those now, and we are now in a good place to start expanding the spec like this.

Related, I'd like to stop including hand-written code examples in the spec, and instead rely on the diagrams we are generating to visually represent the spec (like you have here). So we should create a ticket for that as well.

**Comment by jsign** [comment]
> Going to add all JOIN operators supported in SQLite and
> 
> <img alt="Screen Shot 2022-11-21 at 17 27 31" width="709" src="https://user-images.githubusercontent.com/1233473/203152076-089ac369-3abe-4475-a1eb-fb395ac883de.png">
> 
> all compound operators
> 
> <img alt="Screen Shot 2022-11-21 at 17 28 21" width="387" src="https://user-images.githubusercontent.com/1233473/203152178-5270e924-3a3e-4504-bbfd-6057e648e9a3.png">
> 
> wdyt? @jsign @carsonfarmer

SGTM. The only thing that makes me wonder is if the UNION/INTERSECT/EXCEPT produces deterministic results. 
I'm not sure if the docs say something about it since technically speaking for a SQL result that shouldn't matter.

**Comment by brunocalza** [comment]
I could not find anything in the docs. well. I can force a `ORDER BY rowid` to be safe

**Comment by jsign** [comment]
> I could not find anything in the docs. well. I can force a `ORDER BY rowid` to be safe

I'm not sure if that would work, since if we're making the `UNION` of two tables, there're two potentially overlapping `rowid` values (one for each table). Or maybe I'm confused about the idea.

**Comment by jsign** [comment]
To be more precise: if we have `SELECT A  UNION SELECT B`, even if `SELECT A` and `SELECT B` are deterministic, I'm not sure `UNION` will put all the results from `SELECT A` before the ones from `SELECT B`, or if they might be interleaved if the `UNION` is resolved while both selects are being executed.

**Comment by brunocalza** [comment]
yeah it would not work actually because there would be no `rowid` column in the result of `SELECT A UNION SELECT B`

**Comment by carsonfarmer** [comment]
Also, note that in my reading of various mailing list posts, the is no guarantee of ordering in _any_ SQLite results unless an explicit order-by clause is used. So even if the implementation does produce deterministic results, this is not a guarantee. In practice, it seems that SQLite orders UNION results by the order of the specified expressions (so in the above, it appears in practice that A rows will be before B rows.

**Comment by brunocalza** [comment]
Just too add more info to the thread. The [docs](https://www.sqlite.org/lang_select.html) say the `UNION` operation respects the order specified in the statement:

> When three or more simple SELECTs are connected into a compound SELECT, they group from left to right. In other words, if "A", "B" and "C" are all simple SELECT statements, (A op B op C) is processed as ((A op B) op C).

And also, the query plan suggests an order of operation

```
sqlite> explain query plan select * from t union select * from t2 ;
QUERY PLAN
`--COMPOUND QUERY
   |--LEFT-MOST SUBQUERY
   |  `--SCAN t
   `--UNION USING TEMP B-TREE
      `--SCAN t2
```

So, compound operators seem safe. The problem is the sorting as @carsonfarmer mentioned. Even if we explicitly add an `ORDER BY`, eg `SELECT a FROM t UNION SELECT a FROM t2 ORDER BY a`, we cannot guarantee that the key being sorted is unique and the sorting is stable.
